# Generated by Django 2.2 on 2019-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(default='')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released', models.DateTimeField(blank=True, null=True)),
                ('imbd_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
            ],
        ),
    ]
